<?php

use Illuminate\Database\Seeder;
use App\Party;

class DummyPartiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //`name`, `address`, `party_type`, `vendor_type`
        
        $default_parties = 
            [
                ['M/S Sanjida Plastic(PET)',NULL,2,2],
                ['AB Trade International',NULL,2,2],
                ['Dohar Plastic','',2,2],
                ['H.S. Enterprise','',2,2],
                ['Habib Traders','',2,2],
                ['Khalek & sons','Uttara',2,2],
                ['Rizma Plastic Store','',2,2],
                ['Samuda Chemical (Filler)','',2,2],
                ['Sanjid Plastic Color(HIPS)','',2,2],
                ['Sawdes Plastic','',2,2],
                ['Silva Technologies','',2,2],
                ['OOA',NULL,2,2],
                ['Janata Pet Recycling',NULL,2,2],
                ['R.B Plastic(Pvt)Ltd',NULL,2,2],
                ['Allahar Dan Packing','Uttara',1,2],
                ['Anamul Enterprise','Savar',1,2],
                ['Asha One Time Store','Basundhara',1,2],
                ['Asia Packing Store','Gulshan 02',1,2],
                ['A S Traders','Gazipur',1,1],
                ['Ayesha Varities Store','Gulshan 01',1,2],
                ['Barisal One Time Store','Uttara',1,2],
                ['Bhai Bhai Packeging','Savar',1,2],
                ['Bhai Bhai Varitiy Store','Konabari',1,2],
                ['Bismillah Variety Store','Gulshan 02',1,2],
                ['Bokhtiar & Sons','Tongy',1,2],
                ['Bondhu Packing','Banani',1,2],
                ['Brother Plastic','Gulshan 01',1,1],
                ['Central Warchouse Ananta Energy R.Ltd','Nadda',1,2],
                ['Dragon Breath','Uttara',1,2],
                ['Hanif Traders','Uttara',1,2],
                ['Harivanga Restaurant','Banani',1,1],
                ['Hasan Ppaer House','Tongi',1,1],
                ['Hazi Store','Tongi',1,2],
                ['Maa Fatema Variety  Store','Gulshan 01',1,2],
                ['Maa Packing','Gulshan 02',1,1],
                ['Mainul Haque Traders','Tongi Bazar',1,2],
                ['Mayer Dowa Packing','Banani',1,2],
                ['Mayer Dowa One Time','Jamuna Future Park',1,2],
                ['Mr Anwar Patwary','TSO',1,2],
                ['Mukda Store','Gulshan',1,2],
                ['One Time Packing Store','Jamuna Future Park',1,1],
                ['Ribu Enterprise','Gazipur',1,2],
                ['Sharif Traders','Savar',1,2],
                ['Shohel Paper House','Tongi',1,2],
                ['Susil & Brothers','Joydebpur  Bazar',1,2],
                ['Tea & Me','Banani',1,2],
                ['Ajmary Packing','Kawran Bazar',1,2],
                ['Allahar Dan Store','Kawran Bazar',1,2],
                ['Arif Store','Kawran bazar',1,2],
                ['Arif Store','Tongi',1,2],
                ['Bawniabad Store','Mirpur 11',1,2],
                ['B-Baria Traders','Agargong',1,2],
                ['Bhai Bhai Packeging Store','Kawran Bazar',1,2],
                ['Bhai Bhai Packeging','Boulta  Gausia',1,2],
                ['Bismillah Packing Store','Kawran Bazar',1,2],
                ['Bismillah Packing','New Market',1,2],
                ['Bismillah  Store','Jurain Railgate',1,2],
                ['Bismillah Variety','Mirpur',1,2],
                ['Chadpur Packing','Kawran Bazar',1,2],
                ['Ekota Store','Kawran Bazar',1,2],
                ['Eva  Shopping Center','Mohammadpur',1,2],
                ['Eva Store','Rayer Bazar',1,2],
                ['Feni Store','mirpur 6',1,2],
                ['Habiba Packing Store','Kawran Bazar',1,2],
                ['Hamza One Time Store','Mirpur 1',1,2],
                ['Haque Brothers','New Market',1,2],
                ['Hasan One Time','Mohammadpur',1,2],
                ['Ishan Packing','Mohammadpur',1,2],
                ['Jabed Store','Mohammadpur',1,2],
                ['Jamal Store','Mirpur 1',1,2],
                ['Jointof Trading',NULL,1,2],
                ['Jom Jom Packing','Kawran Bazar',1,2],
                ['Jonodorodi Packing','Kawran Bazar',1,2],
                ['Kashem Store','New Market',1,2],
                ['Kishorgonj Store','Kaptan Bazar',1,2],
                ['Ma Baba Packing','Krishi Market',1,1],
                ['Ma Babar Doya','Mohammadpur',1,2],
                ['Mahin Packing','Kawranbazar',1,2],
                ['Mamun Business Center','Mohammadpur',1,2],
                ['Manik One Time Store','Kawranbazar',1,2],
                ['Mayer Dowa Shopping Center','Khilgong Railgate',1,2],
                ['Mayer doya Traders','Kawran Bazar',1,2],
                ['Milon Chawl Vander','Mohammadpur',1,2],
                ['Mirpur One Time Traders','Mirpur 1',1,2],
                ['Mobakker Store','Malibag Rail Gate',1,2],
                ['New Bhai Bhai Packing','Mohammadpur',1,2],
                ['Noyon Store','Rayer Bazar',1,2],
                ['Omar Shahed  Enterprise',NULL,1,2],
                ['Orbin Tea House','Mohammadpur',1,2],
                ['Oronno Store','Shyamoli',1,2],
                ['Pirojpur Store','Mirpur 13',1,2],
                ['Polithin Corner','Kaptan Bazar',1,2],
                ['Rabbani Store','Malibag',1,2],
                ['Rajdhani Packing','Kawran Bazar',1,2],
                ['Rajib Store','Kathal Bagan',1,2],
                ['Razzak Packing','IKawranbazar',1,2],
                ['RC Cola',NULL,1,2],
                ['Rani Store','Mirpur 11',1,1],
                ['Sabbir Store','Mirpur 11',1,2],
                ['Saikat Packing Store','Kawran Bazar',1,2],
                ['Samira Store',NULL,1,2],
                ['Satota Packing Store','Kawran Bazar',1,2],
                ['Sazid One Time','Mirpur',1,2],
                ['Shamim Store','Mirpur 11',1,2],
                ['Shoriwatpur Gor Vander','Mohammadpur',1,2],
                ['Siam Packaeging','Thatari Bazar',1,2],
                ['S I Dispo','Nilkhet',1,2],
                ['Soikat Store','Mirpur 6',1,2],
                ['Shorna Shopping Center','Mohammadpur',1,1],
                ['Takwa One Time','Mirpur 1',1,2],
                ['Tania One Time Store','New Market',1,2],
                ['Tasin Pack Store','Mohammadpur',1,2],
                ['Tin Bhai Varities Store','Gabtoli Boro Bazar',1,2],
                ['Yousuf Ent.','Mohammadpur',1,1],
                ['Zilani Packing Store','Kawran Bazar',1,2],
                ['Abdur Rasid and Sons','Sylhet',1,2],
                ['Abdur Rouf & Sons','Sylhet',1,2],
                ['Abul Lase','Sylhet',1,2],
                ['Ahmmed & Rahman Traders',NULL,1,2],
                ['A.K Enterprise','Pabna',1,1],
                ['Alif Cookaries','Mymensing',1,2],
                ['Allahar Dan Store','Chittagong',1,2],
                ['Alom Store','Faridpur',1,2],
                ['Amin Store','Feni',1,2],
                ['Ankit Store','Jessore',1,2],
                ['Anwar Dispo','Begum Bazar',1,2],
                ['Apon Traders','Mymensing',1,2],
                ['A R Traders','New Market',1,2],
                ['Ashik & Brothers','Begum Bazar',1,2],
                ['Aziz Corporation','Begum Bazar',1,2],
                ['Barisal One Time Store','Tongi',1,2],
                ['Baro Awlia Dairy Milk & Food','Hosaini Dalan Dhaka',1,2],
                ['Bhai Bhai Cookaries','Gulshan 1',1,2],
                ['Bhai Bhai Store','Chittagong',1,2],
                ['Bishal Traders','Sreemongol',1,2],
                ['Bismillah Despo','Begum Bazar',1,2],
                ['Coffee House','Kamrangichor',1,2],
                ['Coffee Villa',NULL,1,2],
                ['Comilla Jori House','Jessor',1,2],
                ['Daynamic Food','Dhanmondi',1,2],
                ['Emran Enterprise','Saidpur',1,2],
                ['Farid Store','Feni',1,2],
                ['Fresh Dispo','Begumbazar',1,2],
                ['Gaffar','Farmget',1,2],
                ['Gausia Bakery','B-Bariya',1,2],
                ['Gulshan Camical Store',NULL,1,2],
                ['Habib Box House','Tangail',1,2],
                ['Hamid & Son',NULL,1,1],
                ['Hana Trading','Begum Bazar',1,2],
                ['Hanna Store','KawranBazar',1,2],
                ['Hasan Perfumari','Cox Bazar',1,2],
                ['Helal & Brothers','Chittagong',1,2],
                ['Islam Dispo','Begum Bazar',1,2],
                ['Jaiso Chemical','Begum Bazar',1,2],
                ['Jamal Store','Sylhet',1,2],
                ['JK Store','Begum Bazar',1,2],
                ['Jobayer Store','Sylhet',1,2],
                ['Jom Jom Store','Rajshahi',1,2],
                ['Jamuna Printing','Feni',1,2],
                ['Jamuna Store','Begum Bazar',1,2],
                ['Kenakata','Cox Bazar',1,2],
                ['Khokon Store','Tongi Bazar',1,2],
                ['Lamia Dispo','Begum Bazar',1,1],
                ['Lokonath Store','Barisal',1,2],
                ['Loko Sakti Traders','Barishal',1,2],
                ['Mahin & Brothers','Sylhet',1,2],
                ['Majed & Sons','Begum Bazar',1,2],
                ['Maya Store','Mohammadpur',1,2],
                ['Mayer Dowa Store','Gulshan 1',1,2],
                ['M M Trading','Begum Bazar',1,1],
                ['M N Company','Begum Bazar',1,1],
                ['Mobarak Trading','Begum Bazar',1,2],
                ['Mondol Cookaries','Mymensing',1,2],
                ['Mukul Store','Sunamgonj',1,2],
                ['Munna Store','Chittagong',1,2],
                ['Nawrin Store','Chittagong',1,2],
                ['Nihar Ronjon Gosh','Moluvibazar',1,2],
                ['Nilachol Enterprise','Chittagong',1,2],
                ['Niwon Store','Begum Bazar',1,2],
                ['N.M Enterprise','Rajshahi',1,2],
                ['Nupur Store','Town Hall',1,2],
                ['One Time Corner','Tangail',1,2],
                ['One Time Store','Rajshahi',1,2],
                ['Organic Store','Shyamoli adabor',1,2],
                ['Pal Store','Isshordhi',1,2],
                ['Potiya Store','Chittagong',1,2],
                ['Prince Plastic','Comilla',1,2],
                ['Probir Shaha','Nator',1,2],
                ['Prodib Store',NULL,1,2],
                ['Pusty food & Beverage Ltd','Kuril',1,2],
                ['Rajdhani Dodhi','Uttara',1,1],
                ['Rajshahi One Time','Rajshahi',1,2],
                ['Raju Plastic','Comilla',1,2],
                ['Raju Store','Moluvibazar',1,2],
                ['Rakib store','Mymensing',1,2],
                ['Rayan Enterprise','Begum Bazar',1,1],
                ['Rayhan Store','BegumBazar',1,2],
                ['Raid Store','Chapainawabgonj',1,1],
                ['Rose Traders','Khulna',1,2],
                ['Ruma Store','Bhairab',1,2],
                ['Rupali Rice Ghar','Dinajpur',1,2],
                ['Sadiya Kutir Shilpo','Lalbag',1,2],
                ['Sarker Plastic Store','Rajshahi',1,2],
                ['Sarker Store','Rajshahi',1,2],
                ['SB Enterprise','Chittagong',1,2],
                ['Seven Star Packing','Chittagong',1,2],
                ['Sha-Amanat Store','Chittagong',1,2],
                ['Shaha Store','Magura',1,2],
                ['Shamim Dispo','Begum Bazar',1,2],
                ['Shamim Store','Townhall','0.00',1],
                ['Sharia Opset Prash','Hobigonj',1,2],
                ['Shikder & Brothers','Sylhet',1,2],
                ['Shishir Store',NULL,1,2],
                ['Sobuj Gham Tape House','Begum Bazar',1,2],
                ['S.T Enterprise','Rongpur',1,2],
                ['Sumon Plastic House','Chittagong',1,2],
                ['Sumon Store','Begum Bazar',1,2],
                ['Taj Treading','Saidpur',1,2],
                ['Tasnim  Dispo','Begum Bazar',1,2],
                ['Tonmoy Cookeries','Mymensing',1,2],
                ['Tuli Store','Hobigonj',1,2],
                ['Uttam One Time Distributor','Nowgonj',1,2],
                ['Wasim Store','Issordi',1,2],
                ['Zia Shopping Center','Rajshahi',1,2],
                ['Pran RFL Group',NULL,1,1],
                ['Abdul Monem(Igloo)',NULL,1,1],
                ['Amar Tong',NULL,1,1],
                ['Ben Cey Food Products','Adabor',1,1],
                ['Bengal Biscuits Ltd',NULL,1,1],
                ['Beximco Pharmaceuticals Ltd',NULL,1,1],
                ['B.M.P Plan','Kamrangichor',1,1],
                ['BRB Cables Industries Ltd',NULL,1,1],
                ['Ceylon Biscuit Bangladesh Ltd',NULL,1,1],
                ['Chowdhury Enterprise','Begum Bazar',1,1],
                ['Cocola Food Products Ltd',NULL,1,1],
                ['Cookants(Amit)',NULL,1,1],
                ['Coopers','Gulshan 2',1,1],
                ['Cups & Pack Solution','Gulshan 1',1,1],
                ['Danish Foods Limited',NULL,1,1],
                ['Dekko Foods Limited',NULL,1,1],
                ['Dew Touch Bangladesh Limited',NULL,1,1],
                ['Dhaka Ice Cream Industries Ltd(Polar)',NULL,1,1],
                ['Eakin Consumer Food',NULL,1,1],
                ['Ekra Packing','Sylhet',1,1],
                ['Fajitas',NULL,1,1],
                ['F.A Sarder Plastic','Kamrangichor',1,1],
                ['FK Plastic',NULL,1,1],
                ['Hamid Tex Fashion','Hamid Group',1,1],
                ['Haque Limited',NULL,1,1],
                ['Harvest World Agroo Food Ind. Ltd',NULL,1,1],
                ['Hashem Foods Limited','Sajeeb Group',1,1],
                ['Hashy Tiger Co Ltd',NULL,1,1],
                ['Hellow Green','Mirpur',1,1],
                ['Insta Pack',NULL,1,1],
                ['Ismail Hazi',NULL,1,1],
                ['Jabed Agro Food Processing Ltd',NULL,1,1],
                ['June & Jaeif Group',NULL,1,1],
                ['Kazi Food Industries Ltd','Savar',1,1],
                ['Khans Kitchen Limited',NULL,1,1],
                ['Masum Bakery','Dinajpur',1,1],
                ['Mina Dispo Bazar','Begumbazar',1,1],
                ['Montrims Limited(Mondol Group)',NULL,1,1],
                ['Mr Emdadul Haque',NULL,1,1],
                ['Mr Shakil','Sylhet',1,1],
                ['Mr Shiplo',NULL,1,1],
                ['MS Araf Enterprise',NULL,1,1],
                ['Mutual Foam &Tableware Industries Ltd',NULL,1,1],
                ['Nahar Corporation',NULL,1,1],
                ['Peoria Food Products Ltd',NULL,1,1],
                ['Pusti Food',NULL,1,1],
                ['Quazi Food',NULL,1,1],
                ['Quazi Enterprise Limited',NULL,1,1],
                ['Rani Food Industries Ltd',NULL,1,1],
                ['Reedisha Food  & Baverage Ltd',NULL,1,1],
                ['Ren Trade Ent.',NULL,1,1],
                ['RNR Enterprise',NULL,1,1],
                ['Romaniya Food & Baberage Limited',NULL,1,1],
                ['RP Trasers',NULL,1,1],
                ['RS Enterprise',NULL,1,1],
                ['RS Trading',NULL,1,1],
                ['Sanaullah Enterpsise',NULL,1,1],
                ['Shofique Enterprise','Chittagong',1,1],
                ['Six Season Food & Bevarages Ltd',NULL,1,1],
                ['Sonali Bangla Ent.',NULL,1,1],
                ['Sornali Ent.',NULL,1,1],
                ['Square Hospital Ltd',NULL,1,1],
                ['STS Holdings Limited(Apollo)',NULL,1,1],
                ['Swopno',NULL,1,1],
                ['Transcom Bevarage Limited( PEPSI)',NULL,1,1],
                ['Transcom Food Limitd (KFC)',NULL,1,1],
                ['Unimart Limitd(Chef Trading)',NULL,1,1],
                ['Unimart Commercial Enterprise',NULL,1,1],
                ['Allaher Dan Store','Uttara',1,2],
                ['Al Modina varaity store','Gulshan 1',1,2],
                ['A S Traders','Gazipur',1,2],
                ['Azad Beg House','Khilkhet',1,2],
                ['Azmer Packaging','Gulshan 2',1,2],
                ['Bikrampur Store','Tongi',1,2],
                ['Banani Packaging Corner','Bonani',1,2],
                ['Brothers Plastic','Gulshan 1',1,2],
                ['Gram Bangla Foods','Uttara',1,2],
                ['Gulshan Packing Store','Gulshan 2',1,2],
                ['Hari Banga Restaurant','Bonani',1,2],
                ['Hasan Paper House','Tongi',1,2],
                ['Maa Packing(Gulshan-02)','Gulshan-02',1,2],
                ['One Time Packaging Store(Dhaka)','Jamuna Future park',1,2],
                ['Rangpur Confessionary','Gulshan 2',1,2],
                ['Alif Store(New Market)','New Market',1,2],
                ['Biswas Store','Mirpur 2',1,2],
                ['Roni Store','Mirpur 11',1,2],
                ['Sorna ShoppingCenter','Mohammadpur',1,2],
                ['A.K Enterprise','Pabna',1,2],
                ['Jomuna Printing','Begumbazar',1,2],
                ['Md shamim gazi','Narsingdi',1,2],
                ['M.M Trading','Begum Bazar',1,2],
                ['M.N Company','Begum Bazar',1,2],
                ['Mr. Abdul Lotif','Gaibandha',1,2],
                ['Rayhan Enterprise','Begum Bazar',1,2],
                ['Riad Store','Chapainowabgonj',1,2],
                ['Shahjalal Store','Chittagong',1,2],
                ['Pran RFL Group',NULL,1,1],
                ['Igloo-Ice Cream Factor(Abdul Monem)',NULL,1,1],
                ['Amor Tong',NULL,1,1],
                ['Ben Cey Food Production',NULL,1,1],
                ['Hamid Tex Fashion (Group)',NULL,1,1],
                ['Harvest World Agro Food Ind. Ltd. (Uttara)',NULL,1,1],
                ['Hasem Foods Limited(Sajeeb Group)',NULL,1,1],
                ['Hashy Tiger CO Ltd',NULL,1,1],
                ['June & Zaeif Group',NULL,1,1],
                ['Masum Bekary',NULL,1,1],
                ['Montrims Ltd(Mondol Group)',NULL,1,1],
                ['Mr. Shakil',NULL,1,1],
                ['Mr. Shiplu',NULL,1,1],
                ['M/S Araf Enterprise',NULL,1,1],
                ['Mutual Foam And Tableware Industries Ltd',NULL,1,1],
                ['New Olympia',NULL,1,1],
                ['Olympic Industries Limited',NULL,1,1],
                ['R.N.R Enterprise',NULL,1,1],
                ['RP Trasers',NULL,1,1],
                ['RS Trading',NULL,1,1],
                ['STS Holdings Limited(Apollo)',NULL,1,1],
                ['A. S Traders','Gazipur',1,2],
                ['B.Baria Traders','Agargong',1,2],
                ['FM Store(Chock Bazar)',NULL,1,2],
                ['FM Store (Gulshan)',NULL,1,2],
                ['AB Plastic Color',NULL,2,0],
                ['OPENING',NULL,1,2],
                ['OPENING',NULL,2,0],
                ['GIFT',NULL,1,2],
                ['North South University','Bosundhora R/A',1,1],
                ['Square Hospital','Dhanmondi',1,1],
                ['Apollo Hospital','Bosundhora R/A',1,1],
                ['Dhaka Pet Recycling','Satarkul Badda',1,2]

            ];


            foreach($default_parties as $party){
                Party::create([
                    'company_id' => 1,
                    'created_by' => 1,
                    'updated_by' => 1,
                    'name' => $party[0],
                    'address' => $party[1],
                    'party_type' => $party[2],
                    'vendor_type' => $party[3],
                    'status' => 1
                ]);
            }


    }
}
